### ISSUE TITLE
Add runtime error overlay

### ISSUE THREAD

**Issue by einarlove** [unfold/webpack-serve#2]
https://github.com/facebookincubator/create-react-app/commit/ed5c016d6169f0bac7e29625afba1bf7bccac1d9

**Comment by einarlove** [comment]
Not available until new release of react-dev-utils

**Comment by gaearon** [comment]
Fixed by https://github.com/unfold/webpack-serve/commit/a0b8e74cc6083009e24f9f55dfd74b81e8813f5f?

**Comment by einarlove** [comment]
True!
