### ISSUE TITLE
Webpack 3 Support

### ISSUE THREAD

**Issue by athomann** [unfold/webpack-serve#6]
Is the Webpack limitation due to react-dev-utils?  Meaning react-dev-utils would need webpack support before this repo can support?

I'm assuming as soon as https://github.com/facebookincubator/create-react-app/commit/e12d053c273037c5ec75971ddcd117b3e9858cdf is released, this may work?

**Comment by athomann** [comment]
I was able to verify that the `webpack-serve` works when upgrading to Webpack 3.4 and using a local build of latest `create-react-app`.  One issue I ran into was the webpack settings wasn't picking up my proxy settings.  I manually added my proxy settings to the file and that resolved the issue.  But will need to investigate how to dynamically add the proxy settings.

```
  const options = defaults(params, {
    port: process.env.PORT || 8080,
    hostname: process.env.HOSTNAME || 'localhost',
    publicPath: config.output.publicPath,
    contentBase: process.env.CONTENT_BASE || path.resolve('public'),
    https: process.env.HTTPS,
  })
```

**Comment by athomann** [comment]
@gaearon do you have a schedule for the next release bump in https://github.com/facebookincubator/create-react-app ?

**Comment by einarlove** [comment]
Resolved by https://github.com/unfold/webpack-serve/pull/7 which you can get with `npm i @unfold/webpack-serve@^2.0.0`
